services:
  - type: web
    name: stdc-attendance-system
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /index.php
    envVars:
      - key: DB_HOST
        fromService:
          type: database # Changed from 'db' to 'database'
          name: mysql-db
          property: host
      - key: DB_PORT
        fromService:
          type: database
          name: mysql-db
          property: port
      - key: DB_USER
        fromService:
          type: database
          name: mysql-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: database
          name: mysql-db
          property: password
      - key: DB_NAME
        fromService:
          type: database
          name: mysql-db
          property: database

databases:
  - name: mysql-db
    type: postgres # Change 'engine: mysql' to 'type: postgres'
    databaseName: attendancesystem
    user: user
    plan: free
