services:
  - type: web
    name: stdc-attendance-system
    env: apache-php
    plan: free
    healthCheckPath: /index.php
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql-db
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: mysql-db
          property: port
      - key: DB_USER
        fromService:
          type: pserv
          name: mysql-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: mysql-db
          property: password
      - key: DB_NAME
        fromService:
          type: pserv
          name: mysql-db
          property: database
    buildCommand: |
      ls -la
      composer install
      ls -la
    startCommand: |
      # Start Apache in the foreground
      /usr/sbin/apache2ctl -D FOREGROUND
  - type: pserv
    name: mysql-db
    env: mysql
    plan: free
    mysql:
      database: attendancesystem
      user: user
      password: password # Please change this to a strong password
      initializationScriptPath: DATABASE FILE/attendancesystem.sql