services:
  - type: web
    name: stdc-attendance-system
    env: apache-php
    plan: free
    healthCheckPath: /index.php
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql-db
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: mysql-db
          property: port
      - key: DB_USER
        fromService:
          type: pserv
          name: mysql-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: mysql-db
          property: password
      - key: DB_NAME
        fromService:
          type: pserv
          name: mysql-db
          property: database
    buildCommand: |
      composer install
      # The following line will replace the default dbcon.php with a new one that uses the environment variables from Render.
      echo '<?php $conn = new mysqli(getenv("DB_HOST"), getenv("DB_USER"), getenv("DB_PASSWORD"), getenv("DB_NAME")); if($conn->connect_error){ echo "Failed To Connect to database:" . $conn->connect_error; } ?>' > Includes/dbcon.php
    startCommand: |
      # Start Apache in the foreground
      /usr/sbin/apache2ctl -D FOREGROUND
  - type: pserv
    name: mysql-db
    env: mysql
    plan: free
    mysql:
      database: attendancesystem
      user: user
      password: password # Please change this to a strong password
      initializationScriptPath: DATABASE FILE/attendancesystem.sql